name: chengdu80_prototype
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  super_drag_and_drop: ^0.8.24
  cached_network_image: ^3.4.1
  local_hero: ^0.3.0
  supabase_flutter: ^2.8.0
  url_launcher: ^6.3.1
  gauge_indicator: ^0.4.3
  syncfusion_flutter_charts: ^27.1.56
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar/
    - assets/claim/