datas = [
    {
        "title": "Tesla Model Y Engine Fail",
        "amount": 300000,
        "description": "The engine of the Tesla Model Y failed unexpectedly while driving on the highway.",
        "contact": "+86 123 4567 8901",
        "confidence": "High",
        "approve": True,
        "name": "Li Wei",
        "age": 35,
        "location": "Shanghai, China",
        "req_amount": "300000 ",
        "rem_amount": "0 ",
        "human_inter": False,
        "image": "modely.png",
        "brand": "Tesla",
        "model": "Model Y",
    },
    {
        "title": "BMW X5 Collision Damage",
        "amount": 200000,
        "description": "The BMW X5 was involved in a collision with another vehicle, causing significant damage to the front and side panels.",
        "contact": "+86 987 6543 210",
        "confidence": "Medium",
        "approve": True,
        "name": "Wang Fang",
        "age": 42,
        "location": "Beijing, China",
        "req_amount": "200000 ",
        "rem_amount": "0 ",
        "human_inter": False,
        "image": "x5.png",
        "brand": "BMW",
        "model": "X5",
    },
    {
        "title": "Audi Q7 Theft",
        "amount": 400000,
        "description": "The Audi Q7 was stolen from a parking lot. Despite efforts, the vehicle has not been recovered.",
        "contact": "+86 135 7924 6801",
        "confidence": "Low",
        "approve": False,
        "name": "Zhang Ming",
        "age": 29,
        "location": "Guangzhou, China",
        "req_amount": "400000 ",
        "rem_amount": "400000 ",
        "human_inter": True,
        "image": "q7.png",
        "brand": "Audi",
        "model": "Q7",
    },
    {
        "title": "Mercedes-Benz C-Class Fire Damage",
        "amount": 250000,
        "description": "The Mercedes-Benz C-Class caught fire due to an electrical fault while parked in the garage.",
        "contact": "+86 158 3698 7420",
        "confidence": "High",
        "approve": True,
        "name": "Chen Liu",
        "age": 38,
        "location": "Shenzhen, China",
        "req_amount": "250000 ",
        "rem_amount": "0 ",
        "human_inter": False,
        "image": "cclass.png",
        "brand": "Mercedes",
        "model": "C-Class",
    },
    {
        "title": "Toyota Camry Vandalism",
        "amount": 150000,
        "description": "The Toyota Camry was vandalized, resulting in broken windows and extensive body damage.",
        "contact": "+86 147 2583 9630",
        "confidence": "Medium",
        "approve": False,
        "name": "Liu Hong",
        "age": 33,
        "location": "Chengdu, China",
        "req_amount": "150000 ",
        "rem_amount": "150000 ",
        "human_inter": True,
        "image": "camry.png",
        "brand": "Toyota",
        "model": "Camry",
    },
    {
        "title": "Honda Civic Flood Damage",
        "amount": 120000,
        "description": "The Honda Civic was damaged by flood waters during a severe storm.",
        "contact": "+86 156 7890 1234",
        "confidence": "High",
        "approve": True,
        "name": "Zhao Lei",
        "age": 40,
        "location": "Wuhan, China",
        "req_amount": "120000 ",
        "rem_amount": "0 ",
        "human_inter": False,
        "image": "civic.png",
        "brand": "Honda",
        "model": "Civic",
    },
    {
        "title": "BYD Qin Battery Replacement",
        "amount": 250000,
        "description": "Customer reported issues with battery performance.",
        "contact": "135-1234-5678",
        "confidence": "High",
        "approve": False,
        "name": "Li Ming",
        "age": 35,
        "location": "Beijing",
        "req_amount": "300000 ",
        "rem_amount": "50000 ",
        "human_inter": False,
        "image": "qinplus.png",
        "brand": "BYD",
        "model": "Qin Plus",
    },
    {
        "title": "Geely Emgrand X7 Collision Damage",
        "amount": 180000,
        "description": "Vehicle involved in a collision, requiring repairs.",
        "contact": "138-8765-4321",
        "confidence": "Medium",
        "approve": False,
        "name": "Wang Wei",
        "age": 28,
        "location": "Shanghai",
        "req_amount": "200000",
        "rem_amount": "20000",
        "human_inter": False,
        "image": "emgrand.png",
        "brand": "Geely",
        "model": "Emgrand X7",
    },
    {
        "title": "Chery Tiggo 8 Transmission Issue",
        "amount": 220000,
        "description": "Transmission failure reported by the customer.",
        "contact": "137-2468-1357",
        "confidence": "Low",
        "approve": False,
        "name": "Zhang Hua",
        "age": 40,
        "location": "Guangzhou",
        "req_amount": "250000",
        "rem_amount": "30000",
        "human_inter": False,
        "image": "tiggo.png",
        "brand": "Chery",
        "model": "Tiggo 8",
    },
    {
        "title": "Great Wall Haval H6 Engine Overheating",
        "amount": 280000,
        "description": "Customer complained of engine overheating during long drives.",
        "contact": "139-9876-5432",
        "confidence": "High",
        "approve": False,
        "name": "Liu Jing",
        "age": 32,
        "location": "Hangzhou",
        "req_amount": "300000",
        "rem_amount": "20000",
        "human_inter": False,
        "image": "haval.png",
        "brand": "Great Wall",
        "model": "Haval H6",
    },
    {
        "title": "Lynk & Co 01 Brake Failure",
        "amount": 190000,
        "description": "Brake failure reported by the driver, requiring immediate repair.",
        "contact": "136-7654-3210",
        "confidence": "Medium",
        "approve": False,
        "name": "Chen Lei",
        "age": 26,
        "location": "Chengdu",
        "req_amount": "200000",
        "rem_amount": "10000 ",
        "human_inter": False,
        "image": "lynk.png",
        "brand": "Lynk & Co",
        "model": "01",
    },
    {
        "title": "NIO ES8 Battery Degradation",
        "amount": 300000,
        "description": "Customer reported significant battery degradation affecting vehicle performance.",
        "contact": "137-5432-1897",
        "confidence": "High",
        "approve": False,
        "name": "Wu Xia",
        "age": 38,
        "location": "Tianjin",
        "req_amount": "350000 ",
        "rem_amount": "50000 ",
        "human_inter": False,
        "image": "es8.png",
        "brand": "NIO",
        "model": "ES8",
    },
    {
        "title": "Haima S5 Suspension Issue",
        "amount": 210000,
        "description": "Suspension issues reported by the driver, causing discomfort while driving.",
        "contact": "139-6789-5432",
        "confidence": "Low",
        "approve": False,
        "name": "Zhao Yu",
        "age": 31,
        "location": "Nanjing",
        "req_amount": "250000 ",
        "rem_amount": "40000 ",
        "human_inter": False,
        "image": "s5.png",
        "brand": "Haima",
        "model": "S5",
    },
]
